### ISSUE TITLE
Translation: Bahasa Indonesia

### ISSUE THREAD

**Issue by rvlewerissa** [jwasham/google-interview-university#101]
This will be thread for discussing translation related to Bahasa Indonesia!

PR: #100

**Comment by santosomichael** [comment]
Hello, I am Indonesian and I see that you did a great job on translation!! I want to help contribute on this, could you tell me how to start contribute? (I'm still newbie on this github)

**Comment by rvlewerissa** [comment]
@santosomichael Glad someone willing to help!! 

I'm pretty sure you can just push commits to my forked branch :)

So, just:
1. `git clone https://github.com/rvlewerissa/google-interview-university`.
2. `git fetch origin`
3.  'git checkout -b indonesiaTranslation remotes/origin/indonesiaTranslation`
4.  Do translation stuff.
5.  Commit changes.
6.  `git push origin indonesiaTranslation`.

Tell if me anything if you need help :)

**Comment by santosomichael** [comment]
@rvlewerissa Cool!! I will start it soon. Thank you for your help.

**Comment by fahminlb33** [comment]
Hi, I'm also from Indonesia. I'd like to contribute to translate to Indonesia too.

@santosomichael You can't push to the repository because you don't have access.

**Comment by santosomichael** [comment]
@fahminlb33 I think we should use non-formal language, but with proper way. Make reader easier to understand the meaning and enjoy to read.

**Comment by rvlewerissa** [comment]
@fahminlb33 @santosomichael Ah yes, it works automatically if it's we fork a private repo. Could you try again? I add you as a collaborator in my forked repo, probably it would work.

**Comment by wendyliga** [comment]
hey , i'm also interesting contributing in this project , i'm from indonesia

but i'm never doing any project on github before, could you tell me how to start ?

**Comment by rvlewerissa** [comment]
@wendyliga follow https://github.com/jwasham/google-interview-university/issues/101#issuecomment-270204964

**Comment by wendyliga** [comment]
@rvlewerissa so first , make sure i already installed github desktop , then use github cmd like that ?

**Comment by santosomichael** [comment]
@wendyliga hello, wendy, nice to see someone willing to help. so after you install your git on command prompt you could follow the instruction by @rvlewerissa (don't forget to ask for permission from him) and then you should be able to collaborate with us

**Comment by wendyliga** [comment]
@santosomichael  ok , thanks for the guide

**Comment by santosomichael** [comment]
before you do a mistake which I have done a few days ago (haha) read this cool article about [rebase ](https://www.atlassian.com/git/tutorials/merging-vs-rebasing/the-golden-rule-of-rebasing/) you need to use rebase in the future

**Comment by rvlewerissa** [comment]
PR #100 was merged. So feel free to go for a new PR. Thanks.

**Comment by dikiaap** [comment]
Updated #139

**Comment by Chensienyong** [comment]
Looks like the translation for Indonesia is still not finish yet, can I continue to contribute here on this same issue?

**Comment by Myolaw** [comment]
how to play this? how to add a profile photo? I'm still a noob.
