### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Hemko** [jwasham/google-interview-university#124]
Hi
Broken link on "SOLID Design Patterns in C# (video)" / "The playlist does not exist".
https://www.youtube.com/playlist?list=PL8m4NUhTQU48oiGCSgCP1FiJEcg_xJzyQ

**Comment by codehakase** [comment]
@Hemko very true, i just checked it

**Comment by jwasham** [comment]
Thanks @Hemko I removed the link.
