### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by nikolenkoanton92** [jwasham/google-interview-university#13]
Hi John (@jwasham) ,
You have done a very good job. Do you plan to add section about Java?

**Comment by swpnl7** [comment]
Nopes

**Comment by j0ach1mmall3** [comment]
Why nopes?

**Comment by jwasham** [comment]
I'm going to rewrite the languages portion to not favor any specific languages. That started as a personal checklist. 
There are multiple languages that can be used in the interview, as long as they aren't too obscure.

**Comment by jwasham** [comment]
I broke out language resources into a separate file. Please add some Java resources.
https://github.com/jwasham/google-interview-university/blob/master/programming-language-resources.md

**Comment by swpnl7** [comment]
Because I code in c++.

**Comment by nikolenkoanton92** [comment]
@jwasham  nice, thank you
