### ISSUE TITLE
Made by Google Announcement video made private

### ISSUE THREAD

**Issue by AnimeshShaw** [jwasham/google-interview-university#24]
Under the [About Google](https://github.com/jwasham/google-interview-university#about-google) section there's a checkpoint named [Made by Google announcement - Oct 2016 (video)](https://www.youtube.com/watch?v=spDg-Q7zmcM), this video was made private. Shouldn't it be removed?

**Comment by aminought** [comment]
Wow, I've noticed that at the same time too.

**Comment by walcott911** [comment]
I hope it will be reuploaded soon :(

**Comment by jwasham** [comment]
They changed to a different URL. Changed it. Thanks!
