### ISSUE TITLE
How floating point numbers are stored

### ISSUE THREAD

**Issue by aminought** [jwasham/google-interview-university#26]
Now:

- simple 8-bit: Fractions in binary? (video)
- 32 bit: Representation of Floating Point Numbers - 1 (video)
- 64 bit: IEEE754 32-bit floating point binary (video)

Should be:

- simple 8-bit: Representation of Floating Point Numbers - 1 (video)
- 32 bit: IEEE754 32-bit floating point binary (video)
- 64 bit: ???

**Comment by jwasham** [comment]
Thank you. I took care of it.
