### ISSUE TITLE
Problem with lynda.com

### ISSUE THREAD

**Issue by aminought** [jwasham/google-interview-university#30]
> Some videos are available only by enrolling in a Coursera, EdX, or Lynda.com class. These are called MOOCs. It is free to do so, but sometimes the classes are not in session so you have to wait a couple of months, so you have no access.

But lynda.com is not free, is it? Maybe it would be better to replace lynda.com links with something free?

**Comment by jwasham** [comment]
I agree.

**Comment by aminought** [comment]
@jwasham I think, you shouldn't close issues before resolving.)

**Comment by jwasham** [comment]
I see. I agree with replacing the Lynda.com videos with free equivalents. 

Will keep this open if anyone wants to go through and replace them. 

@aminought  So contributors commit against this issue. Is that right?

**Comment by OussamaRomdhane** [comment]
IMHO I think we should keep the lynda.com option and enlist a free alternative with it, leave the choice for the person who is interested in learning one topic or another.
@jwasham You did a great job gathering these ressources by the way, thanks :smile:

**Comment by misalyogeshwar** [comment]
Yes! Please keep lynda.com option. Even if you find free alternatives.

**Comment by jwasham** [comment]
OK. Will do.

**Comment by jwasham** [comment]
I changed the note in README.md to reflect this request.

**Comment by jwasham** [comment]
I'll make a new issue with a clear call to action title and reference this issue.
