### ISSUE TITLE
Translations are welcome

### ISSUE THREAD

**Issue by jwasham** [jwasham/google-interview-university#39]
For those looking to add translated versions, go ahead and do so (using the Chinese translation as an example), and make a pull request.

Please keep your translation updated as the English version changes over time.

Thank you!

**Comment by moinshaikh** [comment]
I'd like to offer a Hindi (India) translation.

P.S.: Best wishes for the journey :)

**Comment by jwasham** [comment]
Thank you @moinshaikh  Please add a translation as a separate file, similar to README-cn.md. Then link to it in the translations section in README.md

**Comment by MrSourabh** [comment]
@moinshaikh Can you please keep me in loop, I would like to help you in that. Thanks

**Comment by sjaramillo10** [comment]
I would like to help with a Spanish (Mexico) translation.
Hope to find someone else to help me too.

**Comment by jwasham** [comment]
Thank you @sjaramillo10 
I appreciate the translations so we can help others.

**Comment by dossorio** [comment]
Hi @sjaramillo10 ! I have forked this repo and added you as collaborator, let's start translating it to Spanish ! 👍

**Comment by jwasham** [comment]
@dossorio I changed the pull request number. I won't pull this one while in progress. I also added "in progress" to the link. Feel free to translate the link, too :)

**Comment by dossorio** [comment]
Awesome 👍  ! Cheers @jwasham

**Comment by jwasham** [comment]
@moinshaikh @MrSourabh is there any progress on a Hindi translation? I can reach out to Twitter if you'd like some help.

**Comment by userimack** [comment]
hi, I can help in hindi translation.

**Comment by MrSourabh** [comment]
hello @jwasham, working on the local as of now... Not much progress... I think I can make good progress by end of this weekend... I'll be in touch with you.. Thanks ! 
@userimack cool... lets get started :)

**Comment by moinshaikh** [comment]
@jwasham I am working on it, shall be updating the doc. within couple of days. 

I am sure books name need not to be translated but still just would like to confirm? (https://github.com/jwasham/google-interview-university#book-list)

BTW, my Twitter is @moingshaikh, am available there all day :)

**Comment by rviquez** [comment]
@dossorio  @sjaramillo10 I would like to help on the translation too. Please let me know how it would be best to proceed

**Comment by dossorio** [comment]
Awesome @rviquez ! 

Open a pr on `dossorio:master` and your changes will be added to that pr 👍  Make sure you have got the latest changes that are on `dossorio:master`

Thanks !!

**Comment by jwasham** [comment]
Thank you for translating!

I made new Issues so you all can coordinate together. 
Please continue the conversation there.

Spanish: #80 - @sjaramillo10 @dossorio @rviquez 
Hindi: #81 - @moinshaikh @MrSourabh @userimack

**Comment by YanaBe** [comment]
Would love to start translating to Hebrew, עברית Shall I begin with the README.md file? Thanks you are an inspiration for my own journey.

**Comment by jwasham** [comment]
Thanks @YanaBe 
Yes: start a new readme, and open an issue as above if anyone wants to help. 
Cheers!

**Comment by jwasham** [comment]
To keep it organized, I added a **translations** directory. Please put new translation README files there.

I'll migrate the existing translations when they are ready.

**To start a new translation**, please:

1. Make an issue (for collaboration with other translators)
2. Make a pull request to collaborate and commit to.
3. Let me know when it's ready to pull.

Thank you!

**Comment by heshamkhamis** [comment]
I would like to help with a Arabic translation.
Hope to find someone translate this Amazing project.

**Comment by Buthaina2018** [comment]
I would like to help with the Arabic translation too.

**Comment by AmrReda** [comment]
I would like to help with the Arabic translation too

**Comment by jwasham** [comment]
@heshamkhamis @AmrReda please join @Buthaina2018 here to collaborate: https://github.com/jwasham/google-interview-university/issues/98

**Comment by ipylypiv** [comment]
I think it is a good idea to put note for all translations that you need to learn English to become Software Engineer at Google.

**Comment by jwasham** [comment]
@ipylypiv in the US, yes, but Google is worldwide.

**Comment by ipylypiv** [comment]
@jwasham It is not about the location. It is about the ecosystem where you will work.
I cannot imagine top-level Software Engineer who don't know English.

Along with tech skills, every Software Engineer must show good soft skills.
Main soft skill is communication (inside team, with management, with customers, etc.)
A friend of mine (born and lived in Ukraine) recently joined Google in Sweden. He don't know a word in Swedish. How can he communicate with others? What about distributed teams between countries?
So it is clear that internal language of top tech companies is English regardless of their locations.

Tech skills are also affected... there are tons of information in English only. Really, imagine that you cannot read comments in the code, documentation, API specification, man page, stackoverflow questions, etc.  without translation.

If you don't know English your communication ability is a **red flag**.

**Comment by santosomichael** [comment]
I would like to help on Indonesian translate, where I could start to contribute? Can't find the 'README-in.md' anywhere on master.  (I'm a newbie)

**Comment by jwasham** [comment]
@santosomichael you went to the right place: #101 
There is work in progress here: #100

**Comment by denizyilmazok** [comment]
@jwasham can we make little additions to make it more understandable ? Because when you write 
> (self-taught,no CS degree)

in Turkish, it is not meaning meaningful. To make it meaningful in Turkish, I need give info about you and what have you done.

**Comment by jwasham** [comment]
@denizyilmazok Feel free to edit for your translation needs. Thank you!

**Comment by jwasham** [comment]
Replaced with: #125
