### ISSUE TITLE
For flashcards I recommended anki

### ISSUE THREAD

**Issue by xiewenya** [jwasham/google-interview-university#54]
For those who what to use flashcards, I recommend Anki. I tried various flashcard apps and Anki is the best. It uses a repetition system to help you remember. It's user friendly, available on all platforms and has a cloud sync system. It costs $25 on ios and free on other platform. 

I have convert your flashcard database to Anki format and shared it on anki website, https://ankiweb.net/shared/info/25173560

**Comment by jwasham** [comment]
Thanks! I'll add a note about it.

**Comment by achmadpanji** [comment]
Thanks
Pada tanggal 24 Okt 2016 00:39, "John Washam" <notifications@github.com>
menulis:
