### ISSUE TITLE
Did you end up at Google

### ISSUE THREAD

**Issue by mohammedzamakhan** [jwasham/google-interview-university#7]
So did you end up joining google 😄 ❓ @jwasham

**Comment by jwasham** [comment]
I still have a few days in the learning phase (finishing up this list), and starting next week all I'll be doing is programming questions all day long. That will continue for a few weeks, and then apply through a referral I've been holding onto since February.

**Comment by AnimeshShaw** [comment]
@jwasham haha I read it in your latest [blog post](https://googleyasheck.com/thanks-everyone/). You are inspiring a lot of people. The # of stargazers will crossover >10k I am sure of it.

**Comment by carise** [comment]
This is really cool, @jwasham ! I wish I found this repo before applying to Google (I had been brushing up on algorithms for 3 months but it still felt like a shoddy effort).

**Comment by jwasham** [comment]
Thanks, everyone! This is very exciting!
