### ISSUE TITLE
I appreciate what you're doing, but this seems absurd

### ISSUE THREAD

**Issue by binoculars** [jwasham/google-interview-university#74]
When companies reach a certain size, these sorts of things happen. They get too big and we end up with people making a study guide for the interview. While I recognize that the information that you've collated here is extremely valuable, I take issue with the fact that it needs to be done at all. We are now past the tipping point where ability to interview is now more valued than talent. I just wish there was more enthusiasm for creativity than there is for hacking a giant company's process. Call me jaded, label me a naysayer, but does anyone actually reflect on why this is so absurd? Don't get me wrong, I love Google and appreciate what they've done for the world, but geez. I think we can all do better. Anyhow, excellent work on putting this together. It helped me learn and I hope it helps others as well, whether they end up at Google or not. Thank you.

**Comment by jwasham** [comment]
HI @binoculars 
Keep in mind that Google was merely a motivator for me. What I was trying to do was go from web developer to software engineer, and most of that was learning what you see here.  It's somewhere close to what would be covered in an undergraduate CS curriculum. 
Google was a great motivator, but not the sole reason.

**Comment by pangjac** [comment]
I love what @jwasham has done and I agree that all his work is just motivated by Google interview, but not limited to this interview process. What is more important to me, is @jwasham 's guide saves a huge amount of time of searching, checking, and asking for what needed to be done.

I have suffered enough of answers like "This is so easy, you can just google it. That's it" or absurd words like "Oh, you don't know that? I think it is very self-explanation, I don't know why you can't get it".  Interesting. Everybody learns from a newbie and seldom they'd love to share the journey. 

Thanks to @jwasham , I could know how to be a better engineer.
