### ISSUE TITLE
Translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by IAMFELIPEMATTOS** [jwasham/google-interview-university#8]
First of all, I want to congratulate you for you huge contribution, because I thought very useful your tips and steps you took, I'm sure it will be very important for someone who has the same desire of you do.

I wanted to do this translation of this repository to Brazilian Portuguese, because I think it will help brazilians anyway.

[**My Translation**](https://github.com/IAMFELIPEMATTOS/google-interview-university/blob/master/README_pt-br.md)

What do you think about the idea?

**Comment by mohammedzamakhan** [comment]
@IAMFELIPEMATTOS Make a pull request. Sounds like great idea

**Comment by jwasham** [comment]
Sounds great. I hope it won't be too much trouble for you keeping it synced as the readme changes. Are you okay with doing that?

**Comment by thierryrene** [comment]
if he does not do, i do 😄 i have the same idea when i see the repo.

**Comment by IAMFELIPEMATTOS** [comment]
we can do it @thierryrene

**Comment by jwasham** [comment]
Go for it!

**Comment by QuantumInformation** [comment]
I would love a Hungarian version. I know that it would help a lot of people in poorer areas in Eastern Europe.

**Comment by jwasham** [comment]
For those looking to add translated versions, go ahead, but please keep them updated as the English version changes over time. I'll make a new issue.

**Comment by QuantumInformation** [comment]
thanks!
